### ISSUE TITLE
Unable to save a document in Public Folder

### ISSUE THREAD

**Issue by rdenarie** [exo-addons/remote-edit#3]
Hello,
I'm trying to use the addon on PLF 4.2.
I log on the platform with john account, and uplaod a document in my "Public" folder.
Then, I choose "Open in Word". My word application opens, I do the modification and save.
Word show me an error : "Unable to upload".
I have a error in my console :
2015-08-28 15:20:38,402 | ERROR | Access denied: REMOVE []:1[]Users:1[]j___:1[]jo___:1[]joh___:1[]john:1[]Public:1[http://www.exoplatform.com/jcr/exo/1.0]thumbnails:1[]7384bff57f00010141761461d77ada66:1 for: john item owner __system [e.j.c.core.SessionActionInterceptor<http-nio-0.0.0.0-8080-exec-10>] 
javax.jcr.AccessDeniedException: Access denied: REMOVE []:1[]Users:1[]j___:1[]jo___:1[]joh___:1[]john:1[]Public:1[http://www.exoplatform.com/jcr/exo/1.0]thumbnails:1[]7384bff57f00010141761461d77ada66:1 for: john item owner __system
	at org.exoplatform.services.jcr.impl.core.SessionDataManager.validateRemoveAccessPermission(SessionDataManager.java:1763) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.SessionDataManager.validateAccessPermissions(SessionDataManager.java:1703) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.SessionDataManager.validate(SessionDataManager.java:1674) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.SessionDataManager.commit(SessionDataManager.java:1561) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.ItemImpl.save(ItemImpl.java:706) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.SessionImpl.save(SessionImpl.java:1121) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.cms.jcrext.activity.EditFilePropertyActivityAction.execute(EditFilePropertyActivityAction.java:52) ~[ecms-core-services-4.2.0.jar:4.2.0]
	at org.exoplatform.services.jcr.impl.ext.action.SessionActionInterceptor.launch(SessionActionInterceptor.java:498) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.ext.action.SessionActionInterceptor.postSetProperty(SessionActionInterceptor.java:351) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.ItemImpl.doUpdateProperty(ItemImpl.java:599) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.ItemImpl.doUpdateProperty(ItemImpl.java:413) ~[exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.impl.core.NodeImpl.setProperty(NodeImpl.java:2284) [exo.jcr.component.core-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.webdav.command.PutCommand.updateContent(PutCommand.java:265) [exo.jcr.component.webdav-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.webdav.command.PutCommand.createVersion(PutCommand.java:209) [exo.jcr.component.webdav-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.webdav.command.PutCommand.put(PutCommand.java:139) [exo.jcr.component.webdav-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.jcr.webdav.WebDavServiceImpl.put(WebDavServiceImpl.java:1079) [exo.jcr.component.webdav-1.15.13-GA.jar:1.15.13-GA]
	at org.exoplatform.services.cms.webdav.WebDavServiceImpl.put(WebDavServiceImpl.java:466) [ecms-core-services-4.2.0.jar:4.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
	at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker$1.run(DefaultMethodInvoker.java:194) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedExceptionAction(SecurityHelper.java:310) [exo.kernel.commons-2.4.13-GA.jar:2.4.13-GA]
	at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:190) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:183) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:657) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:602) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:507) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:146) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.services.rest.servlet.RestServlet.onService(RestServlet.java:85) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.exoplatform.container.web.AbstractHttpServlet.service(AbstractHttpServlet.java:132) [exo.kernel.container-2.4.13-GA.jar:2.4.13-GA]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.exoplatform.services.rest.servlet.RestEncodingFilter.doFilter(RestEncodingFilter.java:58) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.exoplatform.frameworks.jcr.web.ThreadLocalSessionProviderInitializedFilter.doFilter(ThreadLocalSessionProviderInitializedFilter.java:122) [exo.jcr.framework.web-1.15.13-GA.jar:1.15.13-GA]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.exoplatform.services.security.web.SetCurrentIdentityFilter.doFilter(SetCurrentIdentityFilter.java:88) [exo.core.component.security.core-2.5.13-GA.jar:2.5.13-GA]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.55]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.55]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.55]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.55]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.55]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.55]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.55]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) [tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695) [tomcat-coyote.jar:7.0.55]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.55]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

and in access log :
127.0.0.1 - john [28/Aug/2015:15:20:36 +0200] "PUT /rest/private/jcr/repository/collaboration/Users/j___/jo___/joh___/john/Public/TESTS%20PERISCOPE.doc HTTP/1.1" 403 209

If I put my document in a space, the save is working.

When debugging, I could see that the platform try to delete a node in Public/exo:thumbnails/, but it hasn't delete right. 

In space, john a delete right on this folder (group right). In public, he have not.

**Comment by rdenarie** [comment]
Issue raised in Jira : 
https://jira.exoplatform.org/browse/ECMS-7128
So I guess this one can be closed.
